name: Deploy to Server

on:
  push:
    branches:
      - front-end

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASSWORD: ${{ fromJson(vars.APP_CONFIG).DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ fromJson(vars.APP_CONFIG).DOCKER_USERNAME }}
      IMAGE_NAME: ${{ fromJson(vars.APP_CONFIG).IMAGE_NAME }}
      SSH_HOST: ${{ fromJson(vars.APP_CONFIG).SSH_HOST }}
      SSH_PASS: ${{ fromJson(vars.APP_CONFIG).SSH_PASS }}
      SSH_USERNAME: ${{ fromJson(vars.APP_CONFIG).SSH_USERNAME }}
      TAG_NAME: ${{ fromJson(vars.APP_CONFIG).TAG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create .env file
        run: |
          cd backend
          cat <<EOF > .env
          ${{vars.ENV}}
          EOF

      - name: Build Docker image
        run: |
          cd backend
          docker build -t $IMAGE_NAME:$TAG_NAME .

      - name: Add tag docker image (optional)
        run: docker tag $IMAGE_NAME:$TAG_NAME ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}_${{ github.sha }}

      - name: Push Docker image to docker hub (optional)
        run: docker push ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}_${{ github.sha }}

      - name: Copy nginx config & script to server
        run: |
          cd backend
          sshpass -p $SSH_PASS scp -o StrictHostKeyChecking=no -P 24700 ./warning-price-shoppe.conf ./config.sh ${{env.SSH_USERNAME}}@${{env.SSH_HOST}}:/container/

      - name: Deploy to Server (using SSH and Docker)
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 ${{env.SSH_USERNAME}}@${{env.SSH_HOST}} << EOF
            mkdir -p /container && cd /container
            if docker ps -aq --filter name=${{ env.IMAGE_NAME }} | grep -q .; then
                docker stop ${{ env.IMAGE_NAME }} || true
                docker rm -f ${{ env.IMAGE_NAME }} || true
            fi
            if docker images --filter=reference=${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}} --quiet | grep -q .; then
                docker images --filter=reference=${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}} --quiet | xargs -r docker rmi -f
            fi
            docker pull ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}_${{ github.sha }}
            docker run -d -p 3111:3000 --name ${{ env.IMAGE_NAME }} --restart always ${{ env.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.TAG_NAME}}_${{ github.sha }}
          EOF

      - name: Run custom config script on server
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 ${{env.SSH_USERNAME}}@${{env.SSH_HOST}} "cd /container && chmod +x config.sh && ./config.sh"
